#pragma once

/// @internal
/// @file
/// @brief Executor for reflected data members, used by @c SCL_REFLECT_PROPERTY.
///
/// @c property_execution<OuterExecutorType, PropertyTag> is a class template
/// whose nested template @c holder<PropertyType> satisfies the executor concept.
/// It is instantiated as the executor of an inner @c wrapper that proxies a
/// single data member of the outer wrapper's held value.
///
/// @par PropertyTag
/// @p PropertyTag is a struct generated by @c SCL_REFLECT_PROPERTY inside the
/// wrapper class body.  It provides three members used by @c holder:
/// - @c has_override\<E\> — @c true if the outer executor type @c E exposes a
///   static @c property_\<name\>(E) override for the reflected field.
/// - @c override_noexcept\<E\> — @c true iff the override is @c noexcept.
/// - @c call_override(E&&) — invokes the override with the given executor
///   reference and returns its result.
///
/// @par Dispatch in holder::access()
/// When @c PropertyTag::has_override\<exec_refer\> is @c true, @c access()
/// calls the override directly, bypassing @c execute() — analogous to the
/// executor-override path of @c SCL_REFLECT_METHOD.
/// Otherwise, @c access() routes through @c OuterExecutorType::execute(),
/// analogous to the execute-path in @c SCL_REFLECT_METHOD.
///
/// @par Copy / move safety
/// The executor stores a @c ptrdiff_t byte-offset from @c &this to the outer
/// executor, not a raw pointer.  Because the distance between two members of
/// the same class is invariant across all instances, memberwise copy and move
/// of the outer wrapper automatically fix up the pointer — no custom
/// constructors are required.
///
/// @par Thread safety
/// @c guard() / @c unguard() are forwarded to the outer executor when it
/// provides those methods, so thread-safety executors continue to work for
/// property access.

#include <scl/feature/type_traits/executor.h>
#include <scl/utility/type_traits/forward_like.h>

#include <cstddef>
#include <type_traits>
#include <utility>

namespace scl::feature::detail
{
    /// @internal
    /// @brief Executor family for a single reflected data member.
    ///
    /// @tparam OuterExecutorType  The outer wrapper's executor (cv-unqualified).
    /// @tparam PropertyTag        Tag struct generated by @c SCL_REFLECT_PROPERTY;
    ///                            provides override detection and dispatch for this
    ///                            specific field.
    template <typename OuterExecutorType, typename PropertyTag>
    struct property_execution
    {
        /// @internal
        /// @brief Executor for one reflected field of type @p PropertyType.
        ///
        /// @tparam PropertyType  The reference-stripped type of the reflected field;
        ///                       cv-qualifiers on the field are preserved.
        template <typename PropertyType>
        class holder
        {
        public:
            using value_type = PropertyType;

            /// @internal
            /// Non-reference type of the outer executor's held value.
            using outer_value_type = ::std::remove_reference_t<
                decltype(OuterExecutorType::access(::std::declval<OuterExecutorType &>()))>;

            /// @internal
            /// Pointer-to-member type for the reflected field.
            using member_pointer_type = PropertyType outer_value_type::*;

        private:
            ::std::ptrdiff_t m_offset;              ///< Byte offset: @c &this − @c &outer_executor.
            member_pointer_type m_property_pointer; ///< Pointer-to-member for the reflected field.

        private:
            // ── offset-based executor access ──────────────────────────────────

            /// @internal
            /// Returns a pointer to the outer executor, carrying the cv-qualifiers
            /// deduced from @p Self.
            ///
            /// The executor is reached by subtracting the stored byte offset from
            /// the holder's own address (the @c container_of idiom).  The byte
            /// cursor and the result carry the same cv-qualifiers as @p self, so no
            /// @c const or @c volatile is discarded — cv-correctness is established
            /// here instead of relying on every caller to re-apply a @c static_cast.
            ///
            /// @note The offset is recovered from @c &self, which is why @p self is
            ///       not (and cannot be) @c std::forward-ed.
            template <typename Self>
            [[nodiscard]]
            static auto
            outer_exec_ptr(Self && self) noexcept // NOLINT(cppcoreguidelines-missing-std-forward)
                requires ::std::same_as<::std::remove_cvref_t<Self>, holder>
            {
                using exec_obj = ::std::remove_reference_t<::scl::forward_like_t<Self, OuterExecutorType>>;
                using byte_cv = ::std::remove_reference_t<::scl::forward_like_t<Self, ::std::byte>>;

                // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast,cppcoreguidelines-pro-bounds-pointer-arithmetic)
                byte_cv * const cursor = reinterpret_cast<byte_cv *>(&self) - self.m_offset;
                return reinterpret_cast<exec_obj *>(cursor); // NOLINT(cppcoreguidelines-pro-type-reinterpret-cast)
            }

            // ── noexcept predicate for access() ────────────────────────────────

            /// @internal
            /// @c true iff @c access(Self&&) is @c noexcept for the given @p Self.
            ///
            /// Delegates to @c PropertyTag::override_noexcept, which already
            /// returns @c false when no override exists for the given cv-ref.
            template <typename Self>
            static constexpr bool access_noexcept =
                PropertyTag::template override_noexcept<::scl::forward_like_t<Self, OuterExecutorType>>;

        public:
            // ── construction ──────────────────────────────────────────────────

            /// @internal
            /// @note Not @c constexpr: offset computation requires @c reinterpret_cast.
            holder(OuterExecutorType const * exec, member_pointer_type property_pointer) noexcept
                // NOLINTNEXTLINE(cppcoreguidelines-pro-type-reinterpret-cast)
                : m_offset{reinterpret_cast<::std::byte const *>(this) - reinterpret_cast<::std::byte const *>(exec)}
                , m_property_pointer{property_pointer}
            {}

            // ── executor interface ────────────────────────────────────────────

            /// @internal
            /// Returns (a reference to) the reflected field, propagating the
            /// cv-ref qualification of @p self through the outer executor.
            ///
            /// @par Dispatch
            /// -# **Executor-override path** — when @c PropertyTag::has_override\<exec_refer\>
            ///    is @c true, calls @c PropertyTag::call_override() directly,
            ///    bypassing @c execute().  @c noexcept is propagated from the override.
            /// -# **Execute path** — otherwise, routes through
            ///    @c OuterExecutorType::execute(exec, lambda, outer_value) where the
            ///    lambda applies the stored member pointer to @c outer_value.  This
            ///    allows locking or tracing executors to intercept every access.
            template <typename Self>
            static decltype(auto) access(Self && self) noexcept(access_noexcept<Self>)
                requires ::std::same_as<::std::remove_cvref_t<Self>, holder>
            {
                using exec_refer = ::scl::forward_like_t<Self, OuterExecutorType>;

                if constexpr (PropertyTag::template has_override<exec_refer>)
                {
                    return PropertyTag::call_override(
                        ::scl::forward_like<Self>(*outer_exec_ptr(::std::forward<Self>(self))));
                }
                else
                {
                    auto property_pointer = self.m_property_pointer;
                    auto * const exec = outer_exec_ptr(::std::forward<Self>(self));
                    return OuterExecutorType::execute(::scl::forward_like<Self>(*exec),
                        [property_pointer](auto && v) -> decltype(auto) {
                        using property_refer = ::scl::forward_like_t<decltype(v), PropertyType>;
                        return static_cast<property_refer>(::std::forward<decltype(v)>(v).*property_pointer);
                    }, OuterExecutorType::access(::scl::forward_like<Self>(*exec)));
                }
            }

            /// @internal
            /// Forwards @p func to the outer executor's @c execute() in its guard
            /// context.
            ///
            /// @note Unlike @c access(), this overload performs no field projection:
            ///       it neither applies the stored member pointer nor passes the
            ///       wrapped value to @c func.  It is the generic executor-concept
            ///       @c execute used when arbitrary work must run under the outer
            ///       executor's guard; field access is handled exclusively by
            ///       @c access().
            template <typename Self, typename Func>
            static decltype(auto) execute(Self && self, Func && func)
                requires ::std::same_as<::std::remove_cvref_t<Self>, holder>
            {
                return OuterExecutorType::execute(
                    ::scl::forward_like<Self>(*outer_exec_ptr(::std::forward<Self>(self))),
                    ::std::forward<Func>(func));
            }

            // ── optional guard / unguard ──────────────────────────────────────

            /// @internal
            /// Acquires the outer executor's guard (if it has one).
            template <typename Self>
            static void guard(Self && self) /**/
                noexcept(is_guard_noexcept_v<OuterExecutorType, ::scl::forward_like_t<Self, OuterExecutorType>>)
                requires ::std::same_as<::std::remove_cvref_t<Self>, holder> &&
                requires {
                    OuterExecutorType::guard(
                        ::std::declval<::scl::forward_like_t<Self, OuterExecutorType>>());
                }
            {
                OuterExecutorType::guard(
                    ::scl::forward_like<Self>(*outer_exec_ptr(::std::forward<Self>(self))));
            }

            /// @internal
            /// Releases the outer executor's guard (if it has one).
            template <typename Self>
            static void unguard(Self && self) /**/
                noexcept(is_unguard_noexcept_v<OuterExecutorType, ::scl::forward_like_t<Self, OuterExecutorType>>)
                requires ::std::same_as<::std::remove_cvref_t<Self>, holder> &&
                requires {
                    OuterExecutorType::unguard(
                        ::std::declval<::scl::forward_like_t<Self, OuterExecutorType>>());
                }
            {
                OuterExecutorType::unguard(
                    ::scl::forward_like<Self>(*outer_exec_ptr(::std::forward<Self>(self))));
            }
        };
    };
} // namespace scl::feature::detail
