#pragma once

/// @file
/// @brief Internal accessor macros for executor and value access in reflected methods.
/// @ingroup scl_feature_reflection

#include <scl/feature/type_traits/executor.h>

#include <type_traits>

/// @internal
/// @ingroup scl_feature_reflection
/// @brief Obtains the executor in an evaluated context (function body).
///
/// Routes through @c executor_trait so that wrappers that store the executor
/// in a non-default location (not @c m_executor) are handled correctly.
/// Safe here because member function bodies are processed after the class
/// is complete.
///
/// @c static_cast is used rather than @c std::forward because the reflection
/// members are generated inside a mixin base class (@c reflect and its specialisations),
/// where @c *this has the base type, not the derived wrapper type.  A
/// @c static_cast to @c s_c_l_type cv_ref correctly re-establishes the
/// wrapper's identity and value category before passing @c *this to
/// @c executor_trait, whereas @c std::forward would forward a reference to
/// the base subobject.
///
/// @param cv_ref  cv-ref qualifiers applied to the wrapper (@c *this).
#define SCL_EXECUTOR_ACCESS(cv_ref) \
    ::scl::feature::executor_trait<s_c_l_type>::executor(static_cast<s_c_l_type cv_ref>(*this))

/// @internal
/// @ingroup scl_feature_reflection
/// @brief Obtains the wrapped value in an unevaluated context.
///
/// Uses the executor type directly (not the trait) so that the macro
/// works during class definition when the wrapper type is still incomplete.
///
/// @param cv_ref  cv-ref qualifiers applied to the executor.
#define SCL_ACCESS_DECLVAL(cv_ref) \
    s_c_l_executor_type::access(::std::declval<s_c_l_executor_type cv_ref>())

/// @internal
/// @ingroup scl_feature_reflection
/// @brief Obtains the wrapped value in an evaluated context (function body).
///
/// Calls @c Executor::value on the executor obtained via @c SCL_EXECUTOR_ACCESS.
/// Safe here because member function bodies are processed after the class
/// is complete.
///
/// @param cv_ref  cv-ref qualifiers applied to the wrapper (@c *this).
#define SCL_VALUE_ACCESS(cv_ref) s_c_l_executor_type::access(SCL_EXECUTOR_ACCESS(cv_ref))

/// @internal
/// @brief Dispatches a method call through @c Executor::execute.
///
/// Builds the @c execute(exec, callable, args...) call used in every generated
/// overload body.  The callable is a lambda taking @c ScLArgs&&... that
/// applies @c scl::wrapper_cast to each argument and forwards the result to
/// @p method on the wrapped value.
///
/// @param method  Unqualified method name (plain identifier).
/// @param cv_ref  cv-ref qualifiers applied to the wrapper.
#define SCL_EXECUTE_OVERRIDED(name, cv_ref)                           \
    s_c_l_executor_type::execute(SCL_EXECUTOR_ACCESS(cv_ref),         \
        [](auto && scl_v, ScLArgs &&... values) -> decltype(auto) {   \
        return ::std::forward<decltype(scl_v)>(scl_v).name(           \
            ::scl::wrapper_cast(::std::forward<ScLArgs>(values))...); \
    }, SCL_VALUE_ACCESS(cv_ref), ::std::forward<ScLArgs>(scl_args)...)

/// @internal
/// @brief Dispatches an explicit-template-args method call through @c Executor::execute.
///
/// Counterpart of @c SCL_EXECUTE_OVERRIDED for template methods.  The callable
/// uses @p caller to invoke @c .template method\<ScLParam,...\> in a
/// type-dependent context.
///
/// @param caller  Helper struct generated by @c SCL_REFLECT_METHOD (the
///               @c method_##name##_scl_caller type).
/// @param cv_ref  cv-ref qualifiers applied to the wrapper.
#define SCL_EXECUTE_TEMPLATE_OVERRIDED(caller, cv_ref)                                               \
    s_c_l_executor_type::execute(SCL_EXECUTOR_ACCESS(cv_ref),                                        \
        [](auto && scl_v, ScLArgs &&... values) -> decltype(auto) {                                  \
        return caller::template call<ScLParam, ScLParams...>(::std::forward<decltype(scl_v)>(scl_v), \
            ::std::forward<ScLArgs>(values)...);                                                     \
    }, SCL_VALUE_ACCESS(cv_ref), ::std::forward<ScLArgs>(scl_args)...)

/// @internal
/// @brief Obtains the executor from an explicit wrapper parameter (for use in friend function
///        bodies).
///
/// Unlike @c SCL_EXECUTOR_ACCESS, which routes through @c *this, this macro
/// takes an explicit wrapper lvalue/rvalue parameter @p scl_self and forwards
/// it with the correct value category using @c std::forward\<s_c_l_type
/// cv_ref\>.  The two-parameter form is necessary because the friend function
/// has no implicit @c this — the wrapper is passed as an ordinary parameter.
///
/// @param scl_self  The explicit wrapper parameter name.
/// @param cv_ref    cv-ref qualifiers of @p scl_self.
#define SCL_FRIEND_EXECUTOR_ACCESS(scl_self, cv_ref) \
    ::scl::feature::executor_trait<s_c_l_type>::executor(::std::forward<s_c_l_type cv_ref>(scl_self))

/// @internal
/// @brief Obtains the wrapped value from an explicit wrapper parameter.
///
/// Counterpart of @c SCL_VALUE_ACCESS for friend function bodies.
///
/// @param scl_self  The explicit wrapper parameter name.
/// @param cv_ref    cv-ref qualifiers of @p scl_self.
#define SCL_FRIEND_VALUE_ACCESS(scl_self, cv_ref) \
    s_c_l_executor_type::access(SCL_FRIEND_EXECUTOR_ACCESS(scl_self, cv_ref))

/// @internal
/// @brief Dispatches a non-template operator call through @c Executor::execute
///        from a friend function body.
///
/// Counterpart of @c SCL_EXECUTE_OVERRIDED for friend (free-function) operators.
/// Uses @p scl_self (the explicit wrapper parameter) instead of @c *this.
///
/// @param name      Unqualified operator token sequence (plain identifier or
///                  @c operator\ op token sequence).
/// @param scl_self  The explicit wrapper parameter name.
/// @param cv_ref    cv-ref qualifiers of @p scl_self.
#define SCL_FRIEND_EXECUTE_OVERRIDED(name, scl_self, cv_ref)                   \
    s_c_l_executor_type::execute(SCL_FRIEND_EXECUTOR_ACCESS(scl_self, cv_ref), \
        [](auto && scl_v, ScLArgs &&... values) -> decltype(auto) {            \
        return ::std::forward<decltype(scl_v)>(scl_v).name(                    \
            ::scl::wrapper_cast(::std::forward<ScLArgs>(values))...);          \
    }, SCL_FRIEND_VALUE_ACCESS(scl_self, cv_ref), ::std::forward<ScLArgs>(scl_args)...)

/// @internal
/// @brief Dispatches an explicit-template-args operator call through
///        @c Executor::execute from a friend function body.
///
/// Counterpart of @c SCL_EXECUTE_TEMPLATE_OVERRIDED for friend operators.
/// Uses @p scl_self (the explicit wrapper parameter) instead of @c *this.
///
/// @param caller    Helper struct generated by @c SCL_REFLECT_OPERATOR_CALLER.
/// @param scl_self  The explicit wrapper parameter name.
/// @param cv_ref    cv-ref qualifiers of @p scl_self.
#define SCL_FRIEND_EXECUTE_TEMPLATE_OVERRIDED(caller, scl_self, cv_ref)                              \
    s_c_l_executor_type::execute(SCL_FRIEND_EXECUTOR_ACCESS(scl_self, cv_ref),                       \
        [](auto && scl_v, ScLArgs &&... values) -> decltype(auto) {                                  \
        return caller::template call<ScLParam, ScLParams...>(::std::forward<decltype(scl_v)>(scl_v), \
            ::std::forward<ScLArgs>(values)...);                                                     \
    }, SCL_FRIEND_VALUE_ACCESS(scl_self, cv_ref), ::std::forward<ScLArgs>(scl_args)...)

/// @internal
/// @brief Noexcept-safe execute expression for friend operator noexcept specifiers.
///
/// Equivalent to @c SCL_FRIEND_EXECUTE_OVERRIDED but uses
/// @c std::declval\<s_c_l_executor_type cv_ref\>() in place of the real executor
/// obtained via @c executor_trait\<Wrapper\>.  This avoids instantiating
/// @c executor_trait while the wrapper class is still incomplete (GCC 13 evaluates
/// friend-function noexcept specifiers eagerly at class-definition time).
/// Safe in @c noexcept(noexcept(...)) because noexcept is an unevaluated context.
///
/// @param op     The C++ operator token sequence (e.g. @c operator\ +).
/// @param cv_ref cv-ref qualifiers of @p scl_self.
#define SCL_FRIEND_EXECUTE_OVERRIDED_NX(op, cv_ref)                            \
    s_c_l_executor_type::execute(::std::declval<s_c_l_executor_type cv_ref>(), \
        [](auto && scl_v, ScLArgs &&... values) -> decltype(auto) {            \
        return ::std::forward<decltype(scl_v)>(scl_v).op(                      \
            ::scl::wrapper_cast(::std::forward<ScLArgs>(values))...);          \
    }, SCL_ACCESS_DECLVAL(cv_ref), ::std::forward<ScLArgs>(scl_args)...)

/// @internal
/// @brief Noexcept-safe execute expression for friend template-operator noexcept specifiers.
///
/// Equivalent to @c SCL_FRIEND_EXECUTE_TEMPLATE_OVERRIDED but uses
/// @c std::declval\<s_c_l_executor_type cv_ref\>() instead of the real executor.
/// Safe to use in @c noexcept(noexcept(...)) while the wrapper class is incomplete.
///
/// @param caller Helper struct generated by @c SCL_REFLECT_OPERATOR_CALLER.
/// @param cv_ref cv-ref qualifiers of @p scl_self.
#define SCL_FRIEND_EXECUTE_TEMPLATE_OVERRIDED_NX(caller, cv_ref)                                     \
    s_c_l_executor_type::execute(::std::declval<s_c_l_executor_type cv_ref>(),                       \
        [](auto && scl_v, ScLArgs &&... values) -> decltype(auto) {                                  \
        return caller::template call<ScLParam, ScLParams...>(::std::forward<decltype(scl_v)>(scl_v), \
            ::std::forward<ScLArgs>(values)...);                                                     \
    }, SCL_ACCESS_DECLVAL(cv_ref), ::std::forward<ScLArgs>(scl_args)...)

/// @internal
/// @brief Dispatches a reverse-operand binary operator (@c lhs @c op @c value) through
///        @c Executor::execute from a friend function body.
///
/// Used by the reverse-operand hidden friends generated by
/// @c SCL_REFLECT_COMBINED_OPERATOR_IMPL, where the wrapper is the **right** operand and
/// @p scl_lhs is an external (non-wrapper) left operand.  The wrapped value is the right
/// operand of the reflected expression; the call still routes through @c Executor::execute
/// so cross-cutting behaviour applies.
///
/// @param op        The C++ binary operator token (e.g. @c +, @c ==).
/// @param scl_self  The explicit wrapper parameter name.
/// @param scl_lhs   The external left-operand parameter name.
/// @param cv_ref    cv-ref qualifiers of @p scl_self.
#define SCL_FRIEND_REVERSE_EXECUTE(op, scl_self, scl_lhs, cv_ref)                                \
    s_c_l_executor_type::execute(SCL_FRIEND_EXECUTOR_ACCESS(scl_self, cv_ref),                   \
        [](auto && scl_v, auto && scl_l) -> decltype(auto) {                                     \
        return ::std::forward<decltype(scl_l)>(scl_l) op ::std::forward<decltype(scl_v)>(scl_v); \
    }, SCL_FRIEND_VALUE_ACCESS(scl_self, cv_ref), ::std::forward<ScLLhs>(scl_lhs))

/// @internal
/// @brief Noexcept-safe reverse-operand execute expression for friend operator noexcept
///        specifiers.
///
/// Equivalent to @c SCL_FRIEND_REVERSE_EXECUTE but uses
/// @c std::declval\<s_c_l_executor_type cv_ref\>() in place of the real executor, so it is
/// safe to evaluate while the wrapper class is still incomplete (GCC 13 evaluates
/// friend-function noexcept specifiers eagerly at class-definition time).
///
/// @param op     The C++ binary operator token.
/// @param cv_ref cv-ref qualifiers of @p scl_self.
#define SCL_FRIEND_REVERSE_EXECUTE_NX(op, cv_ref)                                                \
    s_c_l_executor_type::execute(::std::declval<s_c_l_executor_type cv_ref>(),                   \
        [](auto && scl_v, auto && scl_l) -> decltype(auto) {                                     \
        return ::std::forward<decltype(scl_l)>(scl_l) op ::std::forward<decltype(scl_v)>(scl_v); \
    }, SCL_ACCESS_DECLVAL(cv_ref), ::std::declval<ScLLhs>())
