#pragma once

/// @file
/// @brief Internal accessor macros for executor and value access in reflected methods.
/// @ingroup scl_feature_reflection

#include <scl/feature/type_traits/executor.h>

#include <type_traits>

/// @internal
/// @ingroup scl_feature_reflection
/// @brief Obtains the executor in an evaluated context (function body).
///
/// Routes through @c executor_trait so that wrappers that store the executor
/// in a non-default location (not @c m_executor) are handled correctly.
/// Safe here because member function bodies are processed after the class
/// is complete.
///
/// @c static_cast is used rather than @c std::forward because the reflection
/// members are generated inside a mixin base class (@c reflect and its specialisations),
/// where @c *this has the base type, not the derived wrapper type.  A
/// @c static_cast to @c s_c_l_type cv_ref correctly re-establishes the
/// wrapper's identity and value category before passing @c *this to
/// @c executor_trait, whereas @c std::forward would forward a reference to
/// the base subobject.
///
/// @param cv_ref  cv-ref qualifiers applied to the wrapper (@c *this).
#define SCL_EXECUTOR_ACCESS(cv_ref) \
    ::scl::feature::executor_trait<s_c_l_type>::executor(static_cast<s_c_l_type cv_ref>(*this))

/// @internal
/// @ingroup scl_feature_reflection
/// @brief Obtains the wrapped value in an unevaluated context.
///
/// Uses the executor type directly (not the trait) so that the macro
/// works during class definition when the wrapper type is still incomplete.
///
/// @param cv_ref  cv-ref qualifiers applied to the executor.
#define SCL_VALUE_DECLVAL(cv_ref) \
    s_c_l_executor_type::value(::std::declval<s_c_l_executor_type cv_ref>())

/// @internal
/// @ingroup scl_feature_reflection
/// @brief Obtains the wrapped value in an evaluated context (function body).
///
/// Calls @c Executor::value on the executor obtained via @c SCL_EXECUTOR_ACCESS.
/// Safe here because member function bodies are processed after the class
/// is complete.
///
/// @param cv_ref  cv-ref qualifiers applied to the wrapper (@c *this).
#define SCL_VALUE_ACCESS(cv_ref) s_c_l_executor_type::value(SCL_EXECUTOR_ACCESS(cv_ref))

/// @internal
/// @brief Dispatches a method call through @c Executor::execute.
///
/// Builds the @c execute(exec, callable, args...) call used in every generated
/// overload body.  The callable is a lambda taking @c ScLArgs&&... that
/// applies @c scl::wrapper_cast to each argument and forwards the result to
/// @p method on the wrapped value.
///
/// @param method  Unqualified method name (plain identifier).
/// @param cv_ref  cv-ref qualifiers applied to the wrapper.
#define SCL_EXECUTE_OVERRIDED(name, cv_ref)                           \
    s_c_l_executor_type::execute(SCL_EXECUTOR_ACCESS(cv_ref),         \
        [](auto && scl_v, ScLArgs &&... values) -> decltype(auto) {   \
        return ::std::forward<decltype(scl_v)>(scl_v).name(           \
            ::scl::wrapper_cast(::std::forward<ScLArgs>(values))...); \
    }, SCL_VALUE_ACCESS(cv_ref), ::std::forward<ScLArgs>(scl_args)...)

/// @internal
/// @brief Dispatches an explicit-template-args method call through @c Executor::execute.
///
/// Counterpart of @c SCL_EXECUTE_OVERRIDED for template methods.  The callable
/// uses @p caller to invoke @c .template method\<ScLParam,...\> in a
/// type-dependent context.
///
/// @param caller  Helper struct generated by @c SCL_REFLECT_METHOD (the
///               @c method_##name##_scl_caller type).
/// @param cv_ref  cv-ref qualifiers applied to the wrapper.
#define SCL_EXECUTE_TEMPLATE_OVERRIDED(caller, cv_ref)                                               \
    s_c_l_executor_type::execute(SCL_EXECUTOR_ACCESS(cv_ref),                                        \
        [](auto && scl_v, ScLArgs &&... values) -> decltype(auto) {                                  \
        return caller::template call<ScLParam, ScLParams...>(::std::forward<decltype(scl_v)>(scl_v), \
            ::std::forward<ScLArgs>(values)...);                                                     \
    }, SCL_VALUE_ACCESS(cv_ref), ::std::forward<ScLArgs>(scl_args)...)
