#pragma once

/// @file
/// @brief Internal accessor macros for executor and value access in reflected methods.
/// @ingroup scl_feature_reflection

#include <scl/feature/type_traits/executor.h>

#include <type_traits>

/// @internal
/// @ingroup scl_feature_reflection
/// @brief Obtains the executor in an evaluated context (function body).
///
/// Routes through @c executor_trait so that wrappers that store the executor
/// in a non-default location (not @c m_executor) are handled correctly.
/// Safe here because member function bodies are processed after the class
/// is complete.
///
/// @c static_cast is used rather than @c std::forward because the reflection
/// members are generated inside a mixin base class (@c reflect and its specialisations),
/// where @c *this has the base type, not the derived wrapper type.  A
/// @c static_cast to @c S_c_L_type_ cv_ref correctly re-establishes the
/// wrapper's identity and value category before passing @c *this to
/// @c executor_trait, whereas @c std::forward would forward a reference to
/// the base subobject.
///
/// @param cv_ref  cv-ref qualifiers applied to the wrapper (@c *this).
#define SCL_EXECUTOR_ACCESS(cv_ref) \
    ::scl::feature::executor_trait<S_c_L_type_>::executor(static_cast<S_c_L_type_ cv_ref>(*this))

/// @internal
/// @ingroup scl_feature_reflection
/// @brief Obtains the wrapped value in an unevaluated context.
///
/// Uses the executor type directly (not the trait) so that the macro
/// works during class definition when the wrapper type is still incomplete.
///
/// @param cv_ref  cv-ref qualifiers applied to the executor.
#define SCL_VALUE_DECLVAL(cv_ref) \
    S_c_L_executor_type_::value(::std::declval<S_c_L_executor_type_ cv_ref>())

/// @internal
/// @ingroup scl_feature_reflection
/// @brief Obtains the wrapped value in an evaluated context (function body).
///
/// Calls @c Executor::value on the executor obtained via @c SCL_EXECUTOR_ACCESS.
/// Safe here because member function bodies are processed after the class
/// is complete.
///
/// @param cv_ref  cv-ref qualifiers applied to the wrapper (@c *this).
#define SCL_VALUE_ACCESS(cv_ref) S_c_L_executor_type_::value(SCL_EXECUTOR_ACCESS(cv_ref))

/// @internal
/// @brief Dispatches a method call through @c Executor::execute.
///
/// Builds the @c execute(exec, callable, args...) call used in every generated
/// overload body.  The callable is a lambda taking @c A_r_g_s__&&... that
/// applies @c scl::wrapper_cast to each argument and forwards the result to
/// @p method on the wrapped value.
///
/// @param method  Unqualified method name (plain identifier).
/// @param cv_ref  cv-ref qualifiers applied to the wrapper.
#define SCL_EXECUTE_OVERRIDED(name, cv_ref)                               \
    S_c_L_executor_type_::execute(SCL_EXECUTOR_ACCESS(cv_ref),            \
        [](auto && S_c_L_v__, A_r_g_s__ &&... values) -> decltype(auto) { \
        return ::std::forward<decltype(S_c_L_v__)>(S_c_L_v__).name(       \
            ::scl::wrapper_cast(::std::forward<A_r_g_s__>(values))...);   \
    }, SCL_VALUE_ACCESS(cv_ref), ::std::forward<A_r_g_s__>(a_r_g_s__)...)

/// @internal
/// @brief Dispatches an explicit-template-args method call through @c Executor::execute.
///
/// Counterpart of @c SCL_EXECUTE_OVERRIDED for template methods.  The callable
/// uses @p caller to invoke @c .template method\<P_a_r_a_m__,...\> in a
/// type-dependent context.
///
/// @param caller  Helper struct generated by @c SCL_REFLECT_METHOD (the
///               @c method_##name##_S_c_L_caller_ type).
/// @param cv_ref  cv-ref qualifiers applied to the wrapper.
#define SCL_EXECUTE_TEMPLATE_OVERRIDED(caller, cv_ref)                                             \
    S_c_L_executor_type_::execute(SCL_EXECUTOR_ACCESS(cv_ref),                                     \
        [](auto && S_c_L_v__, A_r_g_s__ &&... values) -> decltype(auto) {                          \
        return caller::template call<P_a_r_a_m__, P_a_r_a_m_s__...>(                               \
            ::std::forward<decltype(S_c_L_v__)>(S_c_L_v__), ::std::forward<A_r_g_s__>(values)...); \
    }, SCL_VALUE_ACCESS(cv_ref), ::std::forward<A_r_g_s__>(a_r_g_s__)...)
