#pragma once

/// @file
/// @brief Primary template for the reflection mixin chain.
/// @ingroup scl_feature_reflection
///
/// Defines `scl::feature::reflect<Wrapper, Executor, Type>` — the
/// CRTP mixin base that `detail::wrapper` inherits from to acquire all proxy
/// members reflected for the held value type.
///
/// ## How the chain works
///
/// `detail::wrapper<Value, Executor>` publicly inherits:
/// @code{.cpp}
/// reflect<wrapper<Value,Executor>, Executor<Value>, wrapper<Value,Executor>>
/// @endcode
///
/// Two partial specialisations (defined in `detail/wrapper.h`) peel the
/// `detail::wrapper` layer off the third parameter:
///
/// 1. **cv/ref-strip** — `detail::wrapper<QualifiedInner, E>` (where
///    `QualifiedInner` carries cv/ref qualifiers) delegates to the unqualified
///    form, collapsing all 12 variants into one rule.
/// 2. **Chain delegation** — `detail::wrapper<Value, E>` (unqualified inner)
///    inherits from `reflect<Wrapper, Executor, Value>`, propagating
///    all members reflected for `Value` up to the outer wrapper.
///
/// The **primary template** (this file) is the terminal case: when `Type` is
/// neither a `detail::wrapper` specialisation nor any other specialised form,
/// the class body is empty.  User-provided specialisations extend this chain
/// for concrete value types.
///
/// ## Extending for a custom type
///
/// Specialise `reflect` for your value type.
/// `SCL_REFLECT_TYPE` must appear first to establish the internal type
/// context that `SCL_REFLECT_METHOD` depends on:
///
/// @code{.cpp}
/// template <typename Wrapper, typename Executor>
/// class scl::feature::reflect<Wrapper, Executor, MyValue>
/// {
///     SCL_REFLECT_TYPE(Wrapper, Executor)
///     SCL_REFLECT_METHOD(my_method)
/// };
/// @endcode

#include <scl/feature/reflection/method.h>
#include <scl/feature/reflection/operator.h>

namespace scl::feature
{
    /// @brief Primary (terminal) template for the reflection mixin chain.
    /// @ingroup scl_feature_reflection
    ///
    /// Serves as the empty base case of the `reflect` inheritance chain.
    /// `detail::wrapper` inherits (transitively) from this class; each
    /// partial specialisation for a concrete `Type` injects the proxy members
    /// generated by `SCL_REFLECT_METHOD` into the wrapper's public interface.
    ///
    /// When `Type` matches no partial specialisation, this empty body is used —
    /// meaning no extra proxy members are added for that type.
    ///
    /// @tparam Wrapper   The outermost wrapper type that inherits this mixin.
    ///                   Used by `SCL_REFLECT_TYPE` to locate the executor at
    ///                   call time via `scl::feature::executor_trait<Wrapper>`.
    /// @tparam Executor  The outermost executor instantiation
    ///                   (`Executor<Wrapper::value_type>`).  Used internally by
    ///                   the generated proxy methods.
    /// @tparam Type      The type whose reflected members are mixed in.
    ///                   Partial specialisations handle `detail::wrapper`
    ///                   layers (delegating to the inner value type) and
    ///                   concrete value types (injecting proxy members).
    template <typename Wrapper, typename Executor, typename Type>
    class reflect
    {};

    /// @brief CRTP mixin that reflects all standard C++ operators through the executor.
    /// @ingroup scl_feature_reflection
    ///
    /// Inherit from this class to give a wrapper operator forwarding for every
    /// standard C++ operator, constrained by the wrapped type's actual overloads.
    ///
    /// @tparam Wrapper   The outermost wrapper type (CRTP).
    /// @tparam Executor  The executor instantiation for @p Wrapper.
    // NOLINTBEGIN(readability-function-cognitive-complexity, readability-inconsistent-ifelse-braces, cppcoreguidelines-missing-std-forward)
    template <typename Wrapper, typename Executor>
    class reflect_operators
    {
    public:
        SCL_REFLECT_TYPE(Wrapper, Executor)

        SCL_REFLECT_PREFIX_UNARY_OPERATOR(&, address_of)
        SCL_REFLECT_PREFIX_UNARY_OPERATOR(*, indirection)
        SCL_REFLECT_OPERATOR_WITH_ARGUMENTS(->*, arrow_to_pointer)
        SCL_REFLECT_PREFIX_UNARY_OPERATOR(->, arrow)

        SCL_REFLECT_BINARY_OPERATOR(SCL_FORWARD(, ), comma)
        SCL_REFLECT_OPERATOR_WITH_ARGUMENTS([], subscript)
        SCL_REFLECT_OPERATOR_WITH_ARGUMENTS((), call)

        SCL_REFLECT_PREFIX_UNARY_OPERATOR(+, unary_plus)
        SCL_REFLECT_PREFIX_UNARY_OPERATOR(-, unary_minus)
        SCL_REFLECT_PREFIX_UNARY_OPERATOR(++, prefix_increment)
        SCL_REFLECT_PREFIX_UNARY_OPERATOR(--, prefix_decrement)
        SCL_REFLECT_PREFIX_UNARY_OPERATOR(~, bitwise_not)
        SCL_REFLECT_PREFIX_UNARY_OPERATOR(!, logical_not)

        SCL_REFLECT_POSTFIX_UNARY_OPERATOR(++, postfix_increment)
        SCL_REFLECT_POSTFIX_UNARY_OPERATOR(--, postfix_decrement)

        SCL_REFLECT_BINARY_OPERATOR(==, equal_to)
        SCL_REFLECT_BINARY_OPERATOR(!=, not_equal_to)
        SCL_REFLECT_BINARY_OPERATOR(<, less)
        SCL_REFLECT_BINARY_OPERATOR(<=, less_equal)
        SCL_REFLECT_BINARY_OPERATOR(>, greater)
        SCL_REFLECT_BINARY_OPERATOR(>=, greater_equal)

        SCL_REFLECT_BINARY_OPERATOR(*, multiply)
        SCL_REFLECT_BINARY_OPERATOR(/, divide)
        SCL_REFLECT_BINARY_OPERATOR(%, modulo)
        SCL_REFLECT_BINARY_OPERATOR(+, plus)
        SCL_REFLECT_BINARY_OPERATOR(-, minus)

        SCL_REFLECT_BINARY_OPERATOR(<<, left_shift)
        SCL_REFLECT_BINARY_OPERATOR(>>, right_shift)

        SCL_REFLECT_BINARY_OPERATOR(&, bitwise_and)
        SCL_REFLECT_BINARY_OPERATOR(|, bitwise_or)
        SCL_REFLECT_BINARY_OPERATOR(^, bitwise_xor)

        SCL_REFLECT_BINARY_OPERATOR(&&, logical_and)
        SCL_REFLECT_BINARY_OPERATOR(||, logical_or)

        SCL_REFLECT_BINARY_OPERATOR(=, assign) // NOLINT(cppcoreguidelines-c-copy-assignment-signature)
        SCL_REFLECT_BINARY_OPERATOR(*=, multiply_assign)
        SCL_REFLECT_BINARY_OPERATOR(/=, divide_assign)
        SCL_REFLECT_BINARY_OPERATOR(%=, modulo_assign)
        SCL_REFLECT_BINARY_OPERATOR(+=, plus_assign)
        SCL_REFLECT_BINARY_OPERATOR(-=, minus_assign)
        SCL_REFLECT_BINARY_OPERATOR(<<=, left_shift_assign)
        SCL_REFLECT_BINARY_OPERATOR(>>=, right_shift_assign)
        SCL_REFLECT_BINARY_OPERATOR(&=, bitwise_and_assign)
        SCL_REFLECT_BINARY_OPERATOR(|=, bitwise_or_assign)
        SCL_REFLECT_BINARY_OPERATOR(^=, bitwise_xor_assign)
    };
    // NOLINTEND(readability-function-cognitive-complexity, readability-inconsistent-ifelse-braces, cppcoreguidelines-missing-std-forward)

} // namespace scl::feature
