#pragma once

/// @file
/// @brief Primary template for the reflection mixin chain.
/// @ingroup scl_feature_reflection
///
/// Defines `scl::feature::reflect<Wrapper, Executor, Type>` — the
/// CRTP mixin base that `detail::wrapper` inherits from to acquire all proxy
/// members reflected for the held value type.
///
/// ## How the chain works
///
/// `detail::wrapper<Value, Executor>` publicly inherits:
/// @code{.cpp}
/// reflect<wrapper<Value,Executor>, Executor<Value>, wrapper<Value,Executor>>
/// @endcode
///
/// Two partial specialisations (defined in `detail/wrapper.h`) peel the
/// `detail::wrapper` layer off the third parameter:
///
/// 1. **cv/ref-strip** — `detail::wrapper<QualifiedInner, E>` (where
///    `QualifiedInner` carries cv/ref qualifiers) delegates to the unqualified
///    form, collapsing all 12 variants into one rule.
/// 2. **Chain delegation** — `detail::wrapper<Value, E>` (unqualified inner)
///    inherits from `reflect<Wrapper, Executor, Value>`, propagating
///    all members reflected for `Value` up to the outer wrapper.
///
/// The **primary template** (this file) is the terminal case: when `Type` is
/// neither a `detail::wrapper` specialisation nor any other specialised form,
/// the class body is empty.  User-provided specialisations extend this chain
/// for concrete value types.
///
/// ## Extending for a custom type
///
/// Specialise `reflect` for your value type.
/// `SCL_REFLECT_TYPE` must appear first to introduce the
/// `S_c_L_type_` / `S_c_L_executor_type_` aliases that
/// `SCL_REFLECT_METHOD` depends on:
///
/// @code{.cpp}
/// template <typename Wrapper, typename Executor>
/// class scl::feature::reflect<Wrapper, Executor, MyValue>
/// {
///     SCL_REFLECT_TYPE(Wrapper, Executor)
///     SCL_REFLECT_METHOD(my_method)
/// };
/// @endcode

#include <scl/feature/reflection/method.h>

namespace scl::feature
{
    /// @brief Primary (terminal) template for the reflection mixin chain.
    /// @ingroup scl_feature_reflection
    ///
    /// Serves as the empty base case of the `reflect` inheritance chain.
    /// `detail::wrapper` inherits (transitively) from this class; each
    /// partial specialisation for a concrete `Type` injects the proxy members
    /// generated by `SCL_REFLECT_METHOD` into the wrapper's public interface.
    ///
    /// When `Type` matches no partial specialisation, this empty body is used —
    /// meaning no extra proxy members are added for that type.
    ///
    /// @tparam Wrapper   The outermost wrapper type that inherits this mixin.
    ///                   Used by `SCL_REFLECT_TYPE` to locate the executor at
    ///                   call time via `scl::feature::executor_trait<Wrapper>`.
    /// @tparam Executor  The outermost executor instantiation
    ///                   (`Executor<Wrapper::value_type>`).  Exposed as
    ///                   `S_c_L_executor_type_` inside generated proxy methods.
    /// @tparam Type      The type whose reflected members are mixed in.
    ///                   Partial specialisations handle `detail::wrapper`
    ///                   layers (delegating to the inner value type) and
    ///                   concrete value types (injecting proxy members).
    template <typename Wrapper, typename Executor, typename Type>
    class reflect
    {};

} // namespace scl::feature
